# Generated by Django 5.0.4 on 2024-11-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_order_order_status_order_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='state',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
