# Generated by Django 5.0.4 on 2024-11-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_userdetails_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='data_filter',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
