# Generated by Django 5.0.4 on 2024-11-11 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_section_data_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
