# Generated by Django 5.0.4 on 2024-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='delivered',
        ),
    ]
